version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta para conexão do MassTransit
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

  order.api:
    build:
      context: .
      dockerfile: Order.API/Dockerfile
    container_name: order_api
    depends_on:
      - rabbitmq
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__Host: rabbitmq
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=orders;User=user;Password=1234;"
    ports:
      - "5104:5104"
      - "7012:7012"

  payment.api:
    build:
      context: .
      dockerfile: Payment.API/Dockerfile
    container_name: payment_api
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__Host: rabbitmq
    ports:
      - "5140:5140"
      - "7050:7050"

volumes:
  rabbitmq_data:
  mysql_data:
